export { DisplayGenres } from './DisplayGenres';
export { MovieDetails } from './MovieDetails';
export { MoviePageSection } from './MoviePageSection';
export { UpdateDeleteMovie } from './UpdateDeleteMovie';
export { DeleteConfirmationModal } from './DeleteConfirmationModal';
export { EditMovieModal } from './EditMovieModal';
export { AddQuoteModal, ShowMovieExample } from './AddQuoteModal';
export { QuoteCard } from './QuoteCard';
export { QuoteDropdown } from './QuoteDropdown';
export { QuoteDeleteConfirmationModal } from './QuoteDeleteConfirmationModal';
export { EditQuoteModal, EditQuoteModalHeader } from './EditQuoteModal';
export { ViewQuoteModal, ViewQuoteModalHeader } from './ViewQuoteModal';
